### ISSUE TITLE
Cannot play media after calling stop

### ISSUE THREAD

**Issue by MichaelWally-Pray** [Orfium/RxMusicPlayer-android#4]
After sending Stop action to the player no additional media can be played. I believe this occurs because the ExoPlayer is released in PlaybackImpl stopPlayer method and does not appear to be re-initialized.

**Comment by dimkonomis** [comment]
Issue has been fixed in Version 1.0.4.
Just to be clear after sending Stop action you need to call again the start function. If you want just to pause the player just send Pause action.
