### ISSUE TITLE
Calling stop when paused causes IllegalArgumentException

### ISSUE THREAD

**Issue by MichaelWally-Pray** [Orfium/RxMusicPlayer-android#5]
To reproduce: pause media, then call stop

`04-04 15:22:52.278 14666-14666/com.prayapp.client W/System.err: Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.orfium.rx.musicplayer.playback.BasePlayback$audioNoisyReceiver$1@fc2dfe6
04-04 15:22:52.279 14666-14666/com.prayapp.client W/System.err:     at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:793)
04-04 15:22:52.279 14666-14666/com.prayapp.client W/System.err:     at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1203)
04-04 15:22:52.279 14666-14666/com.prayapp.client W/System.err:     at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:576)
04-04 15:22:52.279 14666-14666/com.prayapp.client W/System.err:     at com.orfium.rx.musicplayer.playback.BasePlayback.unregisterNoiseReceiver(BasePlayback.kt:119)
04-04 15:22:52.279 14666-14666/com.prayapp.client W/System.err:     at com.orfium.rx.musicplayer.playback.BasePlayback.stop(BasePlayback.kt:71)
04-04 15:22:52.279 14666-14666/com.prayapp.client W/System.err:     at com.orfium.rx.musicplayer.media.MediaManager.handleStopRequest(MediaManager.kt:120)
04-04 15:22:52.279 14666-14666/com.prayapp.client W/System.err:     at com.orfium.rx.musicplayer.media.MediaManager.access$handleStopRequest(MediaManager.kt:13)
04-04 15:22:52.279 14666-14666/com.prayapp.client W/System.err:     at com.orfium.rx.musicplayer.media.MediaManager$subscribeQueue$state$1.accept(MediaManager.kt:62)
04-04 15:22:52.279 14666-14666/com.prayapp.client W/System.err:     at com.orfium.rx.musicplayer.media.MediaManager$subscribeQueue$state$1.accept(MediaManager.kt:13)
04-04 15:22:52.279 14666-14666/com.prayapp.client W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)`

**Comment by dimkonomis** [comment]
Fixed in version 1.1.0
