### ISSUE TITLE
Dismissing notification only pauses, doesn't stop, audio

### ISSUE THREAD

**Issue by oissa1** [Orfium/RxMusicPlayer-android#7]
If you are playing audio and go to device home screen, then pause and swipe away (dismiss) the notification. Then make a phone call and hang up, then the notification will reappear and audio will start playing again. I think audio should be stopped when a notification is dismissed so that it doesn't start playing again after an audioFocusChange. Or audioFocusedChange should be handled differently? In my fork i just added .setDeleteIntent(dismiss(service)) to the notification.

**Comment by dimkonomis** [comment]
Yes sorry for that, seems i had forgot to add the delete intent to notification. Added in version 1.1.0

**Comment by masudr4n4** [comment]
@dimkonomis  can you pls publish the app to f-droid or playstore or in releases pag so can taste the app
